apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: FAKE_CERT_DATA
    server: https://example.com
  name: example-cluster
contexts:
- context:
    cluster: example-cluster
    user: example-user
  name: example-context
current-context: example-context
kind: Config
preferences: {}
users:
- name: example-user
  user:
    token: FAKE_TOKEN
